name: Acceptance

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - name: Restore .NET dependencies
        run: dotnet restore
      - name: Restore Node.js dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          dotnet build --no-restore --configuration Release -p:Version="${{ steps.vars.outputs.version }}"
